### ISSUE TITLE
Errors while installing with Vundle

### ISSUE THREAD

**Issue by atrioom** [KevinGoodsell/vim-csexact#7] opened 2015-05-04 14:37 UTC
Excerpt from `# >vim +PluginInstall`

```
Done! 
Error detected while processing function <SNR>45_ReadRgbTxt..<SNR>45_FindRgbTxt:
line   11:
E605: Exception not caught: no rgb.txt found, please set g:csexact_rgbtxt
Error detected while processing function <SNR>43_TermFactory:
line   32:
E171: Missing :endif
Error detected while processing function vundle#installer#new..vundle#config#require:
line    5:
E170: Missing :endfor
```

After that `:CSExactColors` puts `E492: Not an editor command: CSExactColors`. 

What is the `rgb.txt` and how do I provide it to the Plugin Installation?

**Comment by KevinGoodsell** [comment] 2015-05-05 01:33
Is this caused specifically by using it with Vundle? Missing rgb.txt file seems the most likely cause.

What Operating System was this observed on? If it's some kind of UNIX-like system, what output do you get when running "locate rgb.txt" in a shell?

Please use ":h g:csexact_rgbtxt" to find the documentation regarding rgb.txt. You don't need this file for installation, but you do need it when the plugin is loaded. You can add the reference to the file post-installation.

**Comment by atrioom** [comment] 2015-05-05 07:50
`locate rgb.txt` puts
```
/opt/X11/share/X11/rgb.txt
/usr/share/emacs/22.1/etc/rgb.txt
```
This is a OSX Yosemite running on my office machine. Yes, this happens when installing it with Vundle, but I assume (though not tested), since Vundle only uses standard Plugin structure to add and remove Plugins, it's not Vundle specific.

`:h g:csexact_rgbtxt` puts `E149: Sorry, no help for g:csexact_rgbtxt`. I guess this is, because the Bundle somehow did not get installed properly? There is another error during installation regarding a missing `endif`.

**Comment by KevinGoodsell** [comment] 2015-05-05 14:34
Yeah, I can't figure out why it's giving a missing endif error. I did find a way to reproduce the problem though, so I can look into it.

I think maybe the help tags haven't been built, so it doesn't know where to find the topic g:csexact_rgbtxt. You can build it with :helptags <path-to-csexact/doc>, or just look at the help online here: https://github.com/KevinGoodsell/vim-csexact/blob/master/doc/CSExact.txt

You should be able to make it work (if it is installed properly) by adding this to your vimrc, above where the plugin is loaded:

let g:csexact_rgbtxt = "/opt/X11/share/X11/rgb.txt"

I'll consider adding that path to the default search paths for the rgb.txt file. Any idea whether that's the usual path on OSX?

**Comment by KevinGoodsell** [comment] 2015-05-05 14:38
Note for reproducing: The code has to be edited to remove the rgb paths (or at least any that actually contain the file on the system you are using); setting g:csexact_rgbtxt to a non-existing path is not sufficient.

The missing endif error is version-specific. Seen on 7.4 but not on 7.2.

**Comment by atrioom** [comment] 2015-05-06 10:26
When I execute `:helptags ~/.vim/bundle/vim-csexact/doc` the command `:h g:csexact_rgbtxt` puts `E149: Sorry, no help for g:csexact_rgbtxt`.
One really noteworthy behaviour I observed was the following:
With `let g:csexact_rgbtxt = "/opt/X11/share/X11/rgb.txt"` right before the Bundle is loaded in .vimrc (`Bundle 'KevinGoodsell/vim-csexact'`) the installtation works without errors. Although after `+PluginInstall` is done, the colorscheme of vim changes to something I don't recognize. I assume that is the Plugin doing its work. There is more: When I invoke ` :CSExactColors` in vim after the installation it puts `E492: Not an editor command: CSExactColors`.
So the +PluginInstall command gets it to work somehow, installs it without errors, but then after that it's gone again. I will have a deeper look into what's happening when I have time this week, other than that I have no input right now, which would be of help solving this. Thanks so far for having a look into this.

**Comment by KevinGoodsell** [comment] 2015-05-06 14:25
Huh, then maybe Vundle is doing something unexpected? You could try manual installation and see if that changes things (just git cloning into .vim/bundle/vim-csexact/ would be enough).

For the help tags, is there a file named "tags" in the doc/ subdir? :helptags is supposed to create that.

**Comment by atrioom** [comment] 2015-05-06 14:32
Exact order of actions: 
-) Removed everything inside vim-csexact folder
-) Cloned the repo with `git clone https://github.com/KevinGoodsell/vim-csexact.git`
-) Started vim without any problems (no error messages or warnings)
-) Executed `:helptags ~/.vim/bundle/vim-csexact/doc`
-) Confirmed existence of `.../doc/tags` file
-) Executed command `:h g:csexact_rgbtxt` without success (same as before)

Content of `tags` file:
```
:CSExactColors	CSExact.txt	/*:CSExactColors*
:CSExactResetColors	CSExact.txt	/*:CSExactResetColors*
CSExact.txt	CSExact.txt	/*CSExact.txt*
csexact-commands	CSExact.txt	/*csexact-commands*
csexact-config	CSExact.txt	/*csexact-config*
csexact-csapprox	CSExact.txt	/*csexact-csapprox*
csexact-install	CSExact.txt	/*csexact-install*
csexact-intro	CSExact.txt	/*csexact-intro*
csexact-issues	CSExact.txt	/*csexact-issues*
csexact-license	CSExact.txt	/*csexact-license*
csexact-support	CSExact.txt	/*csexact-support*
csexact-thanks	CSExact.txt	/*csexact-thanks*
g:csexact_bg_default	CSExact.txt	/*g:csexact_bg_default*
g:csexact_blacklist	CSExact.txt	/*g:csexact_blacklist*
g:csexact_colors_override	CSExact.txt	/*g:csexact_colors_override*
g:csexact_cursor_reset	CSExact.txt	/*g:csexact_cursor_reset*
g:csexact_fg_default	CSExact.txt	/*g:csexact_fg_default*
g:csexact_rgbtxt	CSExact.txt	/*g:csexact_rgbtxt*
g:csexact_term_override	CSExact.txt	/*g:csexact_term_override*
```

**Comment by KevinGoodsell** [comment] 2015-05-07 01:16
Hm, I kind of assumed .vim/bundle/* would be in your Vim runtimepath (which is what happens when you use Pathogen). I'm guessing it's actually not, so :help never looks there. You can confirm this with

:set runtimepath?

You presumably will not see ~/.vim/bundle/vim-csexact in the result. I'm guessing you don't have pathogen, and vundle would normally be responsible for this instead, but for some reason it doesn't seem to be doing the installation properly. I'm guessing if you manually added vim-csexact to runtimepath it would work.

So we know why rgb.txt wasn't found (it's not in one of the expected locations on your system). We probably know why you don't find CSExact items in the help. The "missing endif" error is, I believe, a red herring and just an oddity of Vim's weird exception handling (or a straight-up vim bug). So we're probably left with Vundle acting funny on this plugin. It's hard for me to say because I don't know what Vundle is expected to do. When I have a chance I can install it and see what happens.

**Comment by KevinGoodsell** [comment] 2015-05-07 04:24
I experimented with Vundle and CSExact and found that it works fine for me. I can't see any reason why it wouldn't define the commands and build the help tags (it wouldn't define the commands if the gui feature isn't compiled into Vim, but neither would it change the colors). I suggest clearing out all the other Plugin lines (other than CSExact and Vundle) and trying again. If it still shows that :CSExactColors is not defined, check :set runtimepath? and see if the vim-csexact directory is present.

**Comment by KevinGoodsell** [comment] 2015-05-09 05:17
I just pushed an update to include the /opt/X11/... location for rgb.txt, so you shouldn't need to have g:csexact_rgbtxt set anymore. I can't find any other problems, so unless anyone can provide some additional details I'll close the issue. Thanks, atrioom.

**Comment by atrioom** [comment] 2015-05-11 08:01
Yes, my runtimepath was `runtimepath=~/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim73,/usr/share/vim/vimfiles/after,~/.vim/after,~/.vim/bundle/Vundle.vim`, so you are right, somehow Vundle digs itself in there. I'll try moving my .vim folder and try CSExcact with a completely blank vim.

**Comment by atrioom** [comment] 2015-05-11 08:09
I have exactly the same issues with a blank .vimrc and a blank .vim/bundle folder. Can I ask on which system you are doing your testing? It might be a completely different problem, that has nothing to do with vim or the vim-csexact plugin.

**Comment by KevinGoodsell** [comment] 2015-05-11 14:45
I've done my testing on Debian unstable and an older Debian.

I'm a little unclear on how you set up your last test. If you literally clear out .vimrc, then .vim/bundle has no meaning, and plugins installed there will not work. .vim/bundle is used by plugin managers like pathogen and Vundle; without them vim will ignore it. So if you want to try CSExact on a fresh Vim profile you have to add the csexact directory to your runtimepath yourself.

When I have a little more time I can set up a minimal vim profile and post the details so you can copy it.

**Comment by KevinGoodsell** [comment] 2015-05-12 05:08
Here's a minimal example for testing CSExact:

$ cat .vimrc
set runtimepath+=~/.vim/bundle/vim-csexact

set t_Co=256 " Not generally recommended
syntax on
colorscheme desert

$ find .vim -name .git -prune -o -print
.vim
.vim/bundle
.vim/bundle/vim-csexact
.vim/bundle/vim-csexact/plugin
.vim/bundle/vim-csexact/plugin/CSExact.vim
.vim/bundle/vim-csexact/doc
.vim/bundle/vim-csexact/doc/CSExact.txt
.vim/bundle/vim-csexact/doc/tags
.vim/bundle/vim-csexact/autoload
.vim/bundle/vim-csexact/autoload/csexactdata.vim
.vim/bundle/vim-csexact/autoload/csexact.vim
.vim/bundle/vim-csexact/autoload/rethrow.vim
.vim/bundle/vim-csexact/COPYING

This worked for me under xterm, with TERM=xterm (though usually I have TERM=xterm-256color, and some customized/fixed terminfo entries, but obviously this is not a common setup).

**Comment by KevinGoodsell** [comment] 2015-06-25 02:57
I fixed the rgb.txt location issue and haven't found any other problems with Vundle and CSExact. There are no further actionable items in this issue at this time, so I'm closing it. If a minimal repro can be provided I'll reopen and take another look.

**Closed by KevinGoodsell** 2015-06-25 02:57 UTC
