### ISSUE TITLE
Bad highlight line warning with airblade/vim-gitgutter

### ISSUE THREAD

**Issue by dmfay** [KevinGoodsell/vim-csexact#11] opened 2016-05-29 07:31 UTC
mhinz/vim-signify#45 is a similar issue originally raised for CSApprox. The problem is specifically with a block of sign definitions with nonexistent groupnames from the other plugin:

```
sign define GitGutterLineAdded            linehl=
```

The generated colorscheme translates this to `xxx cleared`, which fails the regex because it doesn't have a groupname. Setting `linehl=NONE` in gitgutter does not raise the warning, but the other issue suggests that that actually creates a bogus groupname and gitgutter is doing things correctly.

**Comment by KevinGoodsell** [comment] 2018-09-03 17:02
Fixed in 2cd4b40ab4caac89a25922e2d8434a52abecfe12.

**Closed by KevinGoodsell** 2018-09-03 17:02 UTC

**Comment by KevinGoodsell** [comment] 2018-09-03 17:07
Also, I just noticed that 2bbdb052d5a477cc8e131283ffb2bc41ee1bdfc6 was intended to handle the same case. Apparently in 2015 I was aware that an empty group name could exist, and it caused problems for the version of the code at the time, so I made changes to account for it, but those changes seem to have been incomplete.

That same commit breaks things in some terminals, see issue #10.
